clear

tic

e=4.80324e-10;

R=1.8;
H=0.2;

% ----- use scale=1 with  GreenFunc180x20.mat for quick estimations ----- % 
scale=10; 

N=scale*180;
M=scale*20; 
K=scale*69+5;
hr=R/N; 
hz=H/M;

Vcb=30/300; 
Vmb=30/300;
Vct=18/300;
Vmt=18/300;
Vgb=-25/300;
Vgt=-25/300;

eps=1e-10;

x=linspace(0,R,N+1);
y=linspace(0,H,M+1);

fitil=zeros(M+1,N+1)-1;
% --------------- boundary conditions on the electrodes ----------------- %
for i=1:N+1
    if (i<=scale*59)
        fitil(1,i)=Vcb;
    elseif (i>scale*59)&&(i<=scale*84)
        fitil(1,i)=Vmb;
    elseif (i>scale*84)&&(i<=scale*104)
        fitil(1,i)=Vgb;
    else
        fitil(1,i)=0;
    end
end     
fitil(:,N+1)=0;
for i=1:N+1
    if (i<=scale*59)
        fitil(M+1,i)=Vct;
    elseif (i>scale*59)&&(i<=scale*84)
        fitil(M+1,i)=Vmt;
    elseif (i>scale*84)&&(i<=scale*104)
        fitil(M+1,i)=Vgt;
    else
        fitil(M+1,i)=0;
    end
end 
% ---------------- relaxation for homogenious solution ------------------ %
max_err=1;
while (max_err>eps)
    for i=1:N+1
        for j=2:M
            a=fitil(j,i);
            if (i==N+1)
                fitil(j,i)=fitil(j,i);
            elseif (i==1)
                fitil(j,i)=(4*(hz/hr)*fitil(j,i+1)+(hr/hz)*fitil(j-1,i)+(hr/hz)*fitil(j+1,i))/(4*hz/hr+2*hr/hz);
            else
                fitil(j,i)=((i-1/2-1)*(hz/hr)*fitil(j,i-1)+(i+1/2-1)*(hz/hr)*fitil(j,i+1)+(i-1)*(hr/hz)*fitil(j-1,i)+(i-1)*(hr/hz)*fitil(j+1,i))/(2*(i-1)*(hz/hr+hr/hz));
            end    
            err(j,i)=abs(fitil(j,i)-a);
        end
    end
    max_err=max(max(err));
end
% ------------- homogen. electric field across the el. layer ------------ %
for i=1:N
    Ertil(i)=(fitil(M/2+1,i)-fitil(M/2+1,i+1))/hr;
    PHI(i)=fitil(M/2+1,i);
end
% ----------- homogen. electric field across the cell's bottom ---------- %
for i=1:N
    EztilBOT(i)=(fitil(1,i)-fitil(2,i))/hz;
end
% ---------------- relaxation for Green func. solution ------------------ %
% ------------------ generated by GreenSOLUT.mat ------------------------ %
%load GreenFunc180x20.mat
load GreenFunc1800x200.mat
% ----------------------------------------------------------------------- %

% ****************** find static density profile ************************ %
% ----------- Green function difference across the el. layer ------------ %
for n=1:N
    for i=1:N
        dGr(n,i)=-4*pi*e*(G(M/2+1,i+1,n)-G(M/2+1,i,n));
    end
end
% ******************* solution with electrons *************************** %
% *********************************************************************** %

for k=1:K
    for i=1:K
        Ertil1(k)=Ertil(k); 
        dGr1(k,i)=dGr(k,i);
    end
end

dens1=Ertil1/dGr1;

for i=1:N
    if (i<=K)
        dens(i)=dens1(i);
    else
        dens(i)=0;
    end
    x1(i)=x(i);
end

% --------------- calculate total number of electrons ------------------- %
for i=1:N+1
    if (i==1)
        A(i)=pi*(hr/2)^2;
    elseif (i==N+1)
        A(i)=pi*(i-5/4)*hr^2;
    else    
        A(i)=2*pi*(i-1)*hr^2;
    end
end
sum=0;
for i=1:N
    sum=sum+A(i)*dens(i);
end
N_total=sum
% ---------------- potential across the liquid surface ------------------ %
dens(N+1)=0;    % add corner point
for i=1:N+1
    for n=1:N+1
        Fr(n,i)=G(M/2+1,i,n);
    end
end    
fir=fitil(M/2+1,:)-4*pi*e*hr*dens*Fr;
% ------------ electric field across the liquid surface ----------------- %
for i=1:N
    Er(i)=(fir(i)-fir(i+1))/hr;
    pot(i)=fir(i);
end
% ----------------------------------------------------------------------- %
figure
subplot(2,1,1)
plot(x,dens)
xlabel('radius (cm)')
ylabel('density (cm^{-2})')
subplot(2,1,2)
plot(x1,300*pot)
xlabel('radius (cm)')
ylabel('Potential (V)')
% ----------------------------------------------------------------------- %

toc

fid=fopen('radius.txt', 'w+');
fprintf(fid, '%e\n', x);
fclose(fid);

fid=fopen('density.txt', 'w+');
fprintf(fid, '%e\n', dens);
fclose(fid);