clear

e=4.80324e-10;              % in CGS
ee=1.6022e-19;              % in SI
me=9.1095e-31;              % in SI

nu=9.6e6;                   % momentum relaxation rate in s^-1
omega_gap=2*pi*76e6;        % gap frequency in s^-1

R=1.8;
H=0.2;

% ----- use scale=1 with  GreenFunc180x20.mat for quick estimations ----- % 
scale=10; 
 
N=scale*180;
M=scale*20; 
K=scale*69+5;
hr=R/N; 
hz=H/M;

load density.txt
for i=1:N+1
    dens(i)=density(i,1);
end

n0=dens(1)*1e4  % density at the center in SI

% ------------------ generated by GreenSOLUT.mat ------------------------ %
%load GreenFunc180x20.mat
load GreenFunc1800x200.mat

Vcb=0.01/300;
Vmb=0.01/300;
Vgb=0/300;
Vct=0/300;
Vmt=0/300;
Vgt=0/300;

tic

eps=1e-10;

x=linspace(0,R,N+1);
y=linspace(0,H,M+1);

fitil=zeros(M+1,N+1)-1/300;
% --------------- boundary conditions on the electrodes ----------------- %
for i=1:N+1
    if (i<=scale*59)
        fitil(1,i)=Vcb;
    elseif (i>scale*59)&&(i<=scale*84)
        fitil(1,i)=Vmb;
    elseif (i>scale*84)&&(i<=scale*104)
        fitil(1,i)=Vgb;
    else
        fitil(1,i)=0;
    end
end     
fitil(:,N+1)=0;
for i=1:N+1
    if (i<=scale*59)
        fitil(M+1,i)=Vct;
    elseif (i>scale*59)&&(i<=scale*84)
        fitil(M+1,i)=Vmt;
    elseif (i>scale*84)&&(i<=scale*104)
        fitil(M+1,i)=Vgt;
    else
        fitil(M+1,i)=0;
    end
end 
% ---------------- relaxation for homogenious solution ------------------ %
max_err=1;
while (max_err>eps)
    for i=1:N+1
        for j=2:M
            a=fitil(j,i);
            if (i==N+1)
                fitil(j,i)=fitil(j,i);
            elseif (i==1)
                fitil(j,i)=(4*(hz/hr)*fitil(j,i+1)+(hr/hz)*fitil(j-1,i)+(hr/hz)*fitil(j+1,i))/(4*hz/hr+2*hr/hz);
            else
                fitil(j,i)=((i-1/2-1)*(hz/hr)*fitil(j,i-1)+(i+1/2-1)*(hz/hr)*fitil(j,i+1)+(i-1)*(hr/hz)*fitil(j-1,i)+(i-1)*(hr/hz)*fitil(j+1,i))/(2*(i-1)*(hz/hr+hr/hz));
            end    
            err(j,i)=abs(fitil(j,i)-a);
        end
    end
    max_err=max(max(err));
end
% ------------ homogen. electric field along the cell's middle ---------- %
for i=1:N
    Ertil(i)=(fitil(M/2+1,i)-fitil(M/2+1,i+1))/hr;
end
% ------------ homogen. electric field across the cell's bottom --------- %
for i=1:N
    Eztil(i)=(fitil(1,i)-fitil(2,i))/hz;
end
% ----------- Green function difference along the charge pool ----------- %
for n=1:N
    for i=1:N
        dGr(n,i)=-4*pi*e*(G(M/2+1,i+1,n)-G(M/2+1,i,n));
    end
end 
% ---------- Green function difference across the cell's bottom --------- %
for n=1:N
    for i=1:N
        dGz(n,i)=-4*pi*e*(G(2,i,n)-G(1,i,n))*(hr/hz);
    end
end

% ************************ solution with electrons ********************** %
% *********************************************************************** %
for i=1:N
    if (i==1)
        A(i)=pi*(hr/2)^2;
    elseif (i==N+1)
        A(i)=pi*(i-5/4)*hr^2;
    else    
        A(i)=2*pi*(i-1)*hr^2;
    end
end
% ----------------- vary freqency of applied exciation ------------------ %
for l=1:101
    
    omega(l)=2*pi*(106e6+(l-1)*5e4);     % angular frequancy in s^-1

    % ------- conductivity \sigma_XX in cgs (1 Simens = 9e11 cgs) ------- %
    sigmaXX=(ee^2*n0/me)*9e11/(nu+complex(0,1)*omega(l)-complex(0,1)*omega_gap^2/omega(l));

    for i=1:N
        sigma(i)=sigmaXX*dens(i)/dens(1);
    end

    % --------- compose and solve matrix continuity equation ------------ %
    for i=1:K
        if (i==1)
            b(i)=(i+1/2-1)*hr*sigma(i)*Ertil(i);
        elseif (i==K)
            b(i)=-(i-1/2-1)*hr*sigma(i-1)*Ertil(i-1);
        else
            b(i)=(i+1/2-1)*hr*sigma(i)*Ertil(i)-(i-1/2-1)*hr*sigma(i-1)*Ertil(i-1);
        end
    end
    deltafunc=eye(N+1,N+1);
    for i=1:K
        if (i==1)
            for j=1:K   
                H(j,i)=(i+1/2-1)*hr*sigma(i)*(dGr(j,i)-dGr(K+1,i)*A(j)/A(K+1))+deltafunc(j,i)*complex(0,1)*omega(l)*A(i)*e/(2*pi);
            end
        else
            for j=1:K   
                H(j,i)=(i+1/2-1)*hr*sigma(i)*(dGr(j,i)-dGr(K+1,i)*A(j)/A(K+1))-(i-1/2-1)*hr*sigma(i-1)*(dGr(j,i-1)-dGr(K+1,i-1)*A(j)/A(K+1))+deltafunc(j,i)*complex(0,1)*omega(l)*A(i)*e/(2*pi);
            end
        end
    end
    dn=b/H;
    % ------------------ use conservation of charge --------------------- %
    dn(K+1)=0;
    for i=1:K
      dn(K+1)=dn(K+1)-A(i)*dn(i)/A(K+1);
    end
    % --------------------- density fluctuations ------------------------ %
    for i=1:N
        if (i<=K+1)
            ddens(i)=dn(i);
        else
            ddens(i)=0;
        end
        x1(i)=x(i);
    end
    % ---------- induced current at the bottom electrodes ---------------- %
    Ez=Eztil-ddens*dGz; % check definition of dGz above! 
    EzCROSS=Eztil;      % check definition of Eztil above!
    I_TOTAL=0;
    I_CROSS=0;
    for i=1:scale*84
      % I_TOTAL=I_TOTAL+A(i+scale*59)*(complex(0,1)*omega(l))*Ez(i+scale*59)/(4*pi);
        %I_CROSS=I_CROSS+A(i+scale*59)*(complex(0,1)*omega(l))*EzCROSS(i+scale*59)/(4*pi);
        I_TOTAL=I_TOTAL+A(i)*(complex(0,1)*omega(l))*Ez(i)/(4*pi);
        I_CROSS=I_CROSS+A(i)*(complex(0,1)*omega(l))*EzCROSS(i)/(4*pi);
    end
    I1=I_TOTAL; % change sign depending on which electrode (+) for inner (-) for middle
    I2=I_CROSS; % change sign depending on which electrode (+) for inner (-) for middle

    Itotal(l)=I1/3e9;      % current in Amp
    Icross(l)=I2/3e9;      % current in Amp
    I(l)=(I1-I2)/3e9;      % current in Amp

    Gp(l)=real(Itotal(l))/0.01;
    Rp(l)=1/Gp(l);
    Cp(l)=imag(Itotal(l))/(0.01*omega(l));

    Cp0(l)=imag(Icross(l))/(0.01*omega(l));
    Cs(l)=Cp(l)*(1+(Gp(l)/(omega(l)*Cp(l)))^2);
    Rs(l)=1/(Gp(l)*(1+(omega(l)*Cp(l)/Gp(l))^2));

    %l

end

toc

figure
subplot(1,2,1)
semilogx(omega/(2*pi)*1e-6,Cp*1e12,omega/(2*pi)*1e-6,Cp0*1e12,'--')
xlabel('\omega/2\pi (MHz)')
ylabel('C_p (pF)')
subplot(1,2,2)
loglog(omega/(2*pi)*1e-6,Rp*1e-6)
xlabel('\omega/2\pi (MHz)')
ylabel('R_p (M\Omega)')

fid=fopen('freq.txt', 'w+');
fprintf(fid, '%e\n', omega/(2*pi));
fclose(fid);

fid=fopen('cap.txt', 'w+');
fprintf(fid, '%f12\n', Cp*1e12);
fclose(fid);

fid=fopen('res.txt', 'w+');
fprintf(fid, '%e\n', Rp);
fclose(fid);


        
        















